app:
  type: dev
postgres:
  host: localhost
  port: 5432
  user: postgres
  pass: postgres
  db: beer
rest:
  listen_host: localhost
  listen_port: 8517
log:
  file_name: beer-rest.log
  path: /var/log/beer-rest
  logdna:
    enabled: True
    key: secret-key
